
service: slack-messenger

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  profile: serverless-admin

  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:*"

plugins:
  - serverless-pseudo-parameters

functions:
  slack:
    handler: handler.handler

